---
  - name: CISCO devices configurations
    hosts: all
    gather_facts: False
    connection: local
    vars:
      ios_provider:
        username: cisco
        password: cisco
      ansible_command_timeout: 60
      
    tasks:
      - name: AAA configurations for cisco devices
        ios_config:
          commands:
            - aaa new-model
            - aaa authentication login default group tacacs+ local
            - aaa authorization exec default group tacacs+ local
            - username cisco privilege 15 secret cisco
            - tacacs-server host 192.168.1.25 key testing123
            - tacacs-server host 192.168.2.25 key testing123
          provider: "{{ ios_provider }}"
      - name: SNMP configurations for cisco devices
        ios_config:
          commands:
            - snmp-server community respirolab RO
            - snmp-server community respirolabwrite RW 10
            - snmp-server trap-source Loopback1
            - snmp-server host 192.168.1.25
            - snmp-server location Sydney
            - snmp-server contact lab@respiro.com.au
            - snmp-server system-shutdown
          provider: "{{ ios_provider }}"
            
