---
  - name: CISCO devices configurations
    hosts: all
    gather_facts: False
    connection: local
    vars:
      ios_provider:
        username: cisco
        password: cisco
      ansible_command_timeout: 60
      
    tasks:
      - name: AAA configuration
        template: src=AAA.j2 dest=configs/AAAauto.cfg
        
      - name: AAA configurations for cisco devices
        ios_config:
          src: "./configs/AAA.cfg"
          provider: "{{ ios_provider }}"
